#!/bin/sh

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

# install python versions using pyenv
. "$DIR/python_versions"

# Pyenv path, shims, and autocompletion
 export PYENV_ROOT="$HOME/.pyenv"
 export PATH="$PYENV_ROOT/bin:$PATH"
 eval "$(pyenv init -)"

 # Tell the shell where virtualenvs live
 mkdir -p $HOME/.virtualenvs
 export WORKON_HOME="$HOME/.virtualenvs"

 # Go and Gopath
 export PATH=$PATH:/usr/local/go/bin:$HOME/dev/bin
 export GOPATH=$HOME/dev

# set default python version
pyenv global 3.5.2 2.7.12

# upgrade pip
pip install --upgrade pip

# install virtualenvwrapper globally
pip install virtualenvwrapper

# install cookiecutter
pip install cookiecutter

# create symlinks for dotfiles
ln -svf $DIR/.spacemacs $HOME/.spacemacs
ln -svf $DIR/.bashrc $HOME/.bashrc
ln -svf $DIR/.gitconfig $HOME/.gitconfig
ln -svf $DIR/.gitignore_global $HOME/.gitignore_global

# fetch Spacemacs Go layer requirements
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/oracle
go get -u -v golang.org/x/tools/cmd/gorename
